version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/choria-io/go-external-agent

    steps:
      - checkout
      - run: go test -v ./...
